/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alibaba_graphscope_utils_NativeUtils */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alibaba_graphscope_utils_NativeUtils
 * Method:    createLoader
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_alibaba_graphscope_utils_NativeUtils_createLoader
  (JNIEnv *, jclass){
      return 0;
  }

#ifdef __cplusplus
}
#endif
